### ISSUE TITLE
Field 'spentBy' may be 'final' 

### ISSUE THREAD

**Issue by adhirmndl** [pradipmudi/expensys#1]
https://github.com/pradipmudi/expensys/blame/1afb2e4ef9e0e22e656724da2f5159971a577b7c/src/main/java/com/expensys/model/enums/SpentBy.java#L7

Non-final field 'spentBy' in enum 'SpentBy'

**Comment by pradipmudi** [comment]
Enum classes in Java are `implicitly final` because they **cannot be extended or subclassed**. Enum constants are predefined instances of the enum class, and you cannot create new ones at runtime. Therefore, there's no need to add the final keyword to the `SpentBy` enum class; it's inherently final by design.
